name: Bwazan
favicon: null
layout_spectrum: 0.6459027277305722
typography_spectrum: 0.45042162807658315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5025781693402678
  lightness: 0.4679891485720873
  saturation: 0.6676851115189493
  rhythmicContrast: 0.6258034727070481
purpose: []
